# Generated by Django 5.0.1 on 2024-02-01 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockCamOzellik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cam_ozellik", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Cam Özellikleri",
            },
        ),
        migrations.CreateModel(
            name="ClockCinsiyet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinsiyet", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Cinsiyetler",
            },
        ),
        migrations.CreateModel(
            name="ClockKasaSekli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kasa_sekli", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Kasa Şekilleri",
            },
        ),
        migrations.CreateModel(
            name="ClockKayisTipi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kayis_tipi", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Kayış Tipleri",
            },
        ),
        migrations.CreateModel(
            name="ClockMarka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=50)),
                (
                    "fotograf",
                    models.ImageField(null=True, upload_to="Marka Fotoğrafları"),
                ),
            ],
            options={
                "verbose_name_plural": "Markalar",
            },
        ),
        migrations.CreateModel(
            name="ClockMekanizma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mekanizma", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Mekanizmalar",
            },
        ),
        migrations.CreateModel(
            name="ClockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Modeller",
            },
        ),
        migrations.CreateModel(
            name="ClockRenk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renk", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Renkler",
            },
        ),
        migrations.CreateModel(
            name="ClockTarz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarz", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Tarzlar",
            },
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.TextField()),
                ("il", models.CharField(max_length=50)),
                ("ilce", models.CharField(max_length=50)),
                ("mahalle", models.CharField(max_length=50)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Adresler",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aciklama", models.TextField()),
                ("fotograf", models.ImageField(upload_to="Ürün Fotoğrafları")),
                ("fiyat", models.FloatField()),
                (
                    "cam_ozellik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockcamozellik",
                    ),
                ),
                (
                    "cinsiyet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockcinsiyet",
                    ),
                ),
                (
                    "kasa_sekli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockkasasekli",
                    ),
                ),
                (
                    "kayis_tipi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockkayistipi",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockmarka",
                    ),
                ),
                (
                    "mekanizma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockmekanizma",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockmodel",
                    ),
                ),
                (
                    "renk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clockrenk",
                    ),
                ),
                (
                    "tarz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.clocktarz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(blank=True, max_length=50, null=True)),
                ("soyad", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(upload_to="Profil Fotoğrafları")),
                (
                    "telefon_numarasi",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dogum_tarihi", models.DateField(blank=True, null=True)),
                (
                    "adres",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appcommerce.adres",
                    ),
                ),
                (
                    "kullanici",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profiller",
            },
        ),
    ]
