# Generated by Django 5.0.1 on 2024-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appcommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name="ClockModel",
        ),
    ]
