# Generated by Django 5.0.1 on 2024-02-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appcommerce", "0002_alter_product_model_delete_clockmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("image", models.ImageField(null=True, upload_to="Marka Fotoğrafları")),
            ],
            options={
                "verbose_name_plural": "Markalar",
            },
        ),
        migrations.CreateModel(
            name="WatchCaseShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_shape", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Kasa Şekilleri",
            },
        ),
        migrations.CreateModel(
            name="WatchColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Renkler",
            },
        ),
        migrations.RenameModel(
            old_name="ClockCinsiyet",
            new_name="WatchGender",
        ),
        migrations.RenameModel(
            old_name="ClockCamOzellik",
            new_name="WatchGlassFeature",
        ),
        migrations.RenameModel(
            old_name="ClockMekanizma",
            new_name="WatchMechanism",
        ),
        migrations.RenameModel(
            old_name="ClockKayisTipi",
            new_name="WatchStrapType",
        ),
        migrations.RenameModel(
            old_name="ClockTarz",
            new_name="WatchStyle",
        ),
        migrations.RenameField(
            model_name="watchgender",
            old_name="cinsiyet",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="watchglassfeature",
            old_name="cam_ozellik",
            new_name="glass_feature",
        ),
        migrations.RenameField(
            model_name="watchmechanism",
            old_name="mekanizma",
            new_name="mechanism",
        ),
        migrations.RenameField(
            model_name="watchstraptype",
            old_name="kayis_tipi",
            new_name="strap_type",
        ),
        migrations.RenameField(
            model_name="watchstyle",
            old_name="tarz",
            new_name="style",
        ),
        migrations.AlterField(
            model_name="product",
            name="marka",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Appcommerce.watchbrand"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kasa_sekli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Appcommerce.watchcaseshape",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="renk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Appcommerce.watchcolor"
            ),
        ),
        migrations.DeleteModel(
            name="ClockMarka",
        ),
        migrations.DeleteModel(
            name="ClockKasaSekli",
        ),
        migrations.DeleteModel(
            name="ClockRenk",
        ),
    ]
