# Generated by Django 5.0.1 on 2024-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appcommerce", "0004_basketproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profil",
            name="ad",
        ),
        migrations.RemoveField(
            model_name="profil",
            name="soyad",
        ),
    ]
