# Generated by Django 5.0.1 on 2024-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appcommerce", "0006_alter_basketproduct_options_favoriteproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adres",
            name="adres",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adres",
            name="il",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="adres",
            name="ilce",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="adres",
            name="mahalle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
